= Complete Database Guide

Once you have the couch-db container running, you should be able to access your Couch Database by going to `+http://[pi-ip-addr]:5984/_utils+` in a web browser, using the ip address of your pi.

We use CouchDB as the database for our solution. Apache CouchDB is an open-source document-oriented NoSQL database
that uses JSON documents to store data. For more information about CuchDB specifically please refer to their http://docs.couchdb.org/en/stable/intro/index.html[documentation].
 
Within CouchDB there are five important tables that are used throughout our solution:

. xref:devices.adoc[devices]
. xref:device_type.adoc[device_type]
. xref:rooms.adoc[rooms]
. xref:buildings.adoc[buildings]
. xref:room_configurations.adoc[room_configurations]

This guide will outline each of the tables above, their purpose, what data is being stored, and how it is used within our AV solution.

*_Please note that the documents below are meant to explain each of the tables and a illustrate what data is stored in each of the documents. These examples are not the meant to be copied and pasted for the demo._* 

The exact documents that you need for terms of this demo can be found xref:DemoDB.adoc[here]

=== Local vs. Central DB Setup

Our current infrastructure utilizes both central and local databases. We deployed our central database in AWS and each pi has its own local database. 

*_Central Database_*: Stored in AWS. Contains all tables used for our organization (not only the ones required for the av-api).

*_Local Database_*: When the Pi is deployed and configured for a room, a script runs that replicates the five required tables (mentioned above) from our central DB in AWS to the pi locally.

=== Setting Up Central DB and Replication

After setting up a central DB in a remote location you can set up replication for each of the databses tables from the remote DB. for additional information and documentation on how to implement replication in your solution, please refer to https://guide.couchdb.org/draft/replication.html[Couch's Replication Documentation].