= Complete Database Guide

Once you have the couch-db container running, you should be able to access your Couch Database by going to `+http://[pi-ip-addr]:5984/_utils+` in a web browser, using the ip address of your pi.

We use CouchDB as the database for our solution. Apache CouchDB is an open-source document-oriented NoSQL database
that uses JSON documents to store data. For more information about CouchDB specifically please refer to their http://docs.couchdb.org/en/stable/intro/index.html[documentation].
 
Within CouchDB there are five important tables that are used throughout our solution:

. xref:devices.adoc[devices]
. xref:device_type.adoc[device_type]
. xref:rooms.adoc[rooms]
. xref:buildings.adoc[buildings]
. xref:room_configurations.adoc[room_configurations]

This guide will outline each of the tables above, their purpose, what data is being stored, and how it is used within our AV solution.

*_Please note that the documents below are meant to explain each of the tables and a illustrate what data is stored in each of the documents. These examples are not the meant to be copied and pasted for the demo._* 

If you are looking for the exact documents needed for this demo, or even a script that automatically imports them into your database, both can be found xref:DemoDBScript.adoc[here]. 

==== Up Next:
xref:devices.adoc[devices table]