= Complete OS Setup Guide

=== Getting the OS ready

To get the Operating System ready, you need a raspberry pi with the following installed on it:

* xref:OS.adoc#_raspbian[raspbian]
* xref:OS.adoc#_docker[docker]
* xref:OS.adoc#_docker_compose[docker-compose]
* xref:OS.adoc#_web_browser[web browser and window manager]

=== raspbian
This section will outline the necessary steps to get a raspbian image up and running on your raspberry pi. Here are the steps you take:

* Download the 'Raspbian Buster Lite' image https://www.raspberrypi.org/downloads/raspbian/[here].
* Using the https://www.balena.io/etcher/[Balena Etcher utility], flash the downlaoded image to an SD card.
** If you want to enable ssh by default, now is the time.  With the SD card still connected to your computer, add an empty file called `+ssh+` to the `+boot+` directory on the SD card.
* Place the SD card into the Pi and connect it to the network and turn in on.
** The default username is `+Pi+` and the password is `+raspberry+`
** On first boot you may need to change keyboard settings and enable ssh (if you haven't already).  You can use the built in config utility called `+raspi-config+` (run that command after logging in).

*NOTE: When you are running the following commands you need to prefix each command with `+sudo+` if you get a permission error. Alternatively you can run `+sudo su+` first and all subsequent commands will be run with "root" priviledges.

=== docker
These are the commands to get https://www.docker.com/why-docker[docker] on your raspberry pi: 

[source,bash]
----
curl -fsSL https://get.docker.com | sh
usermod -aG docker pi

systemctl enable docker # make sure it starts at login
----

=== docker-compose
These are the commands to get https://docs.docker.com/compose/[docker-compose] on your raspberry pi:

[source,bash]
----
apt update
apt -y install python3 python3-pip libffi-dev
pip3 install docker-compose

reboot
----

=== web browser and window manager
These are the commands to get the chromium web browser and the https://i3wm.org/[i3 window manager] on your raspberry pi:

[source,bash]
----
apt update
apt install -y chromium-browser i3 xserver-xorg xinit

reboot
----

Once installed, you will need to setup i3 to launch from the console on login.  First we need to create a config file for i3:

[source,bash]
----
mkdir .i3
cp etc/i3/config .i3/config
----

Then you need to create a file called .xinitrc (in the pi user's home directory) with the following contents:

----
#!/user/bin/env bash

screenshutoff
exec i3
----

Once created, you need to give the file execute permissions:


[source, bash]
----
chmod +x ~/.xinitrc
----

And last, you need to create a file called .bash_profile (also in the home directory) with the following contents.  This will launch i3 whenever you login as the `+pi+` user from the console (not ssh).

----
if [[ -z $DISPLAY && $(tty) == /dev/tty1 ]]; then
        startx -- -nocursor
fi

source ~/.bashrc

----