= Quick Start

Here you will find a quick start guide to getting your environment set up to use the av-control-api to communicate with devices in your classroom. For the distribution of our content we use Docker simply for the ease of containerization, distribution, and use for our systems.You are of course able to pull down our repositories, compile the binaries, and launch the microservices independently, but feel free to use our already packaged Docker containers as well. For additional information about Docker please refer to https://docs.docker.com/engine/docker-overview/[Docker's Docs].

There are many differrent ways to implement our AV solution in your organization. We will not outline each type of implementation but rather will outline
the steps to one implementation method and allow others to be creative in how they want to implement our solution in their organization.

== Demo Solution

For the purpose of this demo we will be setting up a single display room that is controlled by a raspberry pi running the AV-API. The raspberry pi will act as the room's control system and be able to control the input being shown on the display as well as the volume of the display. For this demo you will need the following materials:

* https://www.raspberrypi.org/products/raspberry-pi-4-model-b/[Raspberry Pi 4 Model B]
* https://www.raspberrypi.org/products/raspberry-pi-touch-display/[7-inch Rapsberry Pi Touch Panel]
* An IP controllable display (one which we xref:hardwareList.adoc[have already written a driver for])
** For demonstration purposes we will be using a https://www.sony.com/electronics/televisions/xbr-x800g-x805g-x807g-series[Sony XBR 800G]

This setup guide should help you get your first room up and running, using the av-control-api to control it and optionally one of our UI's. _This UI is *not* a production UI, rather a simple interface that was been created for sole purpose of this demo_.

The basic sections are as follows:

. Getting the hardware set up
. Getting the OS ready
. Downloading/starting the av-control-api docker containers and (optionally) a basic UI container
. Setting up the database and configuring your devices
. Testing the API
. Using the UI
. Exploring BYU's Implementation

== Getting the hardware set up

For more detailed information on how to set up the devices for this demo please see the xref:hardwareSetup.adoc[Hardware Setup Guide]. This guide will also outline any necssary configurations that need to be in place for the AV-API to work.

== Getting the OS ready

To get the Operating System ready to go for this solution you need a raspberry pi with the following installed on it:

* raspbian
* docker
* docker-compose
* web browser

For a detailed step-by-step guide to get these installed on your raspberry pi, please refer to the xref:OS.adoc[Complete OS Setup Guide]

== Downloading and Starting Necesary Docker Containers

To get the Pi up and running to control the sample room the following containers are needed:

. https://github.com/byuoitav/couch-db-repl[couch-db (for configuration storage)]
. https://github.com/byuoitav/av-api[av-api (base api engine)]
. https://github.com/byuoitav/sony-control-microservice[sony-control-microservice (sony adcp protocol translation service)]
. https://github.com/byuoitav/demoUI[Demo UI]

Once you have each of these containers you will need a docker-compose.yml file for each of the containers.

Use docker-compose to get the containers up and running on your pi. For more detailed steps on how to accomplish this step please refer to xref:startAPI.adoc[Starting the AV API].

== Setting up the database and configuring your devices

We use CouchDB as the database for our solution. Within CouchDB there are five important tables that are used throughout our solution:

. devices
. device_type
. rooms
. buildings
. room_configurations

For a more detailed documentation on the content of each of these tables, their purpose, and how they relate to each other, 
please refer to the xref:DB.adoc[Complete Database Guide]

== Testing the API

Once you have followed the previous steps, you should be set to begin testing the API. Attempt to hit the API endpoints using a program like
Postman. If it is successful then you have successfully set up your pi to control the devices in your room. For more detailed documentation
on how to test the API enpoints please refer to the xref:API.adoc[Complete API Testing Guide]

== Using the UI

The UI is awesome. Figure out how it works xref:UI.adoc[here].

== Exploring BYU's Implementation

BYU's implementation  is awesome. Figure out how it works xref:byuArchitecture.adoc[here].

