=== room_configurations

Each room may have the same or different system architectures. The room_configurations database contains data on various system architectures.
The room configuration refers to a block of code and determines what actions are being sent. These actions are http requests that are
made to specific microservices.The data below is then used for these actions.
----
{
  "_id": "Default", // <1>
  "_rev": "2-d2e604ba3d31eba5636da22beccedcfe", // <1>
  "evaluators": [ // <2>
    {
      "_id": "PowerOnDefault", // <3>
      "codekey": "PowerOnDefault", // <4>
      "description": "PowerOnDefault", // <5>
      "priority": 1 // <6>
    },
    {
      "_id": "StandbyDefault",
      "codekey": "StandbyDefault",
      "description": "StandbyDefault",
      "priority": 9999
    },
    {
      "_id": "ChangeAudioInputDefault",
      "codekey": "ChangeAudioInputDefault",
      "description": "ChangeAudioInputDefault",
      "priority": 1337
    },
    {
      "_id": "MuteDefault",
      "codekey": "MuteDefault",
      "description": "MuteDefault",
      "priority": 5
    },
    ... //there are other evaluators not included in this sample
  ],
  "description": "Default" // <1>
}
----
<1> These fields are identical to the fields mentioned in detail in previous examples.
<2> `+"evaluators"+`: This is where you are going to hit the API endpoints. We currently run docker containers on the rapsberry pi so it is localhost.
<3> `+"_id"+`: Id of the evaluator
<4> `+"codekey"+`: The codekey is a key in a map of commands that is used to determine what command needs to be sent for the room/device.
<5> `+"description"+`: Description of the evaluator.
<6> `+"priority"+`: This designates the order in which the actions are executed. (i.e. if a power on action and a change input action are both
executed you want the power on action to have a lower number in the priority field than the change input - designating that the power on action
will execute before the change input action will execute.)
