= Downloading and Starting Necesary Docker Containers

We will be using docker-compose to get the required contianers up and running on your pi.

Please follow the steps below:

. ssh into your pi by running `+ssh [ip-address-of-pi]+`
.. if there is default username and password the username is "pi" and the password is "raspberry"
. use the the editor of your choice to add the text below to a file named `+docker-compose.yml+`
. After saving the file, run `+docker-compose up+`
. The docker containers are now running. You can verify that the containers are up by using `+docker ps+`
----
version: '3'
services:
    couch-db:
        image: treehouses/rpi-couchdb:2.1.1
        ports:
            - "5984:5984"
        network_mode: "host"
        restart: always
        tty: true
    av-api:
        image: byuoitav/rpi-av-api:latest
        ports:
           - "8000:8000"
        environment:
            - BYPASS_AUTH=true
            - SYSTEM_ID=DEMO-123-CP1
            - ROOM_SYSTEM=true
            - DB_ADDRESS=http://localhost:5984
            - HUB_ADDRESS=localhost:7100
            - STOP_REPLICATION=true
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=AVAPIPASSWORD
        network_mode: "host"
        restart: always
        tty: true
    sony-control-microservice:
        image: byuoitav/rpi-sony-control-microservice:latest
        ports:
            - "8012:8012"     
        environment:
            - SYSTEM_ID=BLDG-ROOM-CP1
            - BYPASS_AUTH=true
            - ROOM_SYSTEM=true 
            - SONY_TV_PSK=AVAPI              
        network_mode: "host"
        restart: always
        tty: true
    demoUI:
        image: byuoitav/demoUI:latest
        ports:
            - "8081:8081"              
        network_mode: "host"
        restart: always
        tty: true
----


If you are interested in looking at the code found in each of these containers, the repositories are found below.:

. https://github.com/byuoitav/couch-db-repl[couch-db (for configuration storage)]
. https://github.com/byuoitav/av-api[av-api (base api engine)]
. https://github.com/byuoitav/sony-control-microservice[sony-control-microservice (sony adcp protocol translation service)]
. https://github.com/byuoitav/demoUI[Demo UI]


Once you have the couch-db container running, you should be able to access it by going to `+http://[pi-ip-addr]:5984/_utils+`  in a web browser, using the ip address of your pi.

You will need to create several databases and documents for a base configuration. These documents will be detailed in the next section: xref:DB.adoc[Complete Database Guide]

After you have added the required documents in your database you are ready to test the API endpoints! Please refer to the xref:API.adoc[Complete API Testing Guide] for more information.
