name: Build
on:
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Set up go
              uses: actions/setup-go@v1
              with:
                  go-version: 1.14.x

            - name: Set up node
              uses: actions/setup-node@v1

            - name: Check out code
              uses: actions/checkout@v1

            - name: Build
              run: make
